server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://${eureka.instance.hostname}:${server.port}/eureka}
  server:
    enable-self-preservation: false
  security:
    username: ${EUREKA_SECURITY_USERNAME}
    password: ${EUREKA_SECURITY_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
